import puppeteer from "puppeteer-core";
import { mkdirSync, writeFileSync } from "node:fs";
import { strict as assert } from "node:assert";
import { fixtureMessages, fixtureText } from "../tests/helpers/chat-fixture.ts";

process.env.SOCIETY_DATABASE_FILE = ":memory:";
process.env.SOCIETY_OPERATOR_TOKEN = "ui-test-operator";
process.env.SOCIETY_MODEL_SETTINGS_FILE = "data/ui-models-test.json";
mkdirSync("data/v2-ui", { recursive: true });
process.env.SOCIETY_CHARACTERS_FILE = "data/v2-ui/characters-test.json";
writeFileSync(process.env.SOCIETY_CHARACTERS_FILE, JSON.stringify({ characters: [] }));
const { context, createServerApp } = await import("../src/server/index.ts");
const { RunService } = await import("../src/runtime/run.ts");
const { runSpecSchema } = await import("../src/runtime/types.ts");
const { runtimeCharacter } = await import("../src/server/routes/runs.ts");
context.runs = new RunService(context.runs.store, () => ({ async turn(c) {
  if (c.opportunity.actions.length) {
    for (const action of c.opportunity.actions) await c.call(action.name, { amount: Math.min(5, action.fields[0].max) });
    return {};
  }
  return { waited: true };
} }));
const characters = context.characters.list().builtins.slice(0, 2).map(runtimeCharacter);
const spec = runSpecSchema.parse({ scenario: "trust-game", rounds: 2, roster: characters.map(c => ({ characterId: c.id, human: true })) });
const created = context.runs.create(spec, characters);
const server = await new Promise(resolve => { const s = createServerApp().listen(0, "127.0.0.1", () => resolve(s)); });
const base = `http://127.0.0.1:${server.address().port}`;
mkdirSync("data/v2-ui", { recursive: true });
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_BIN ?? "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe", headless: true });
try {
  const page = await browser.newPage(); const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.setViewport({ width: 1440, height: 1000 });
  await page.goto(base, { waitUntil: "networkidle2" });
  await page.goto(`${base}/#/settings`, { waitUntil: "networkidle2" });
  await page.locator('[role="tab"] ::-p-text(管理访问)').click();
  await page.type('#operator-token', process.env.SOCIETY_OPERATOR_TOKEN);
  await page.locator('button ::-p-text(保存管理令牌)').click();
  await page.waitForFunction(() => document.querySelector('#operator-token').value === "" && localStorage.getItem('society:owner-token') === 'ui-test-operator');
  await page.goto(base, { waitUntil: "networkidle2" });
  await page.evaluate(({ id, ownerToken, playerTokens }) => { localStorage.setItem(`society:run:${id}:owner`, ownerToken); sessionStorage.setItem(`society:run:${id}:players`, JSON.stringify(playerTokens)); }, { id: created.run.id, ownerToken: created.ownerToken, playerTokens: created.playerTokens });
  await page.screenshot({ path: "data/v2-ui/home-desktop.png", fullPage: true });
  await page.setViewport({ width: 390, height: 844 });
  await page.screenshot({ path: "data/v2-ui/home-mobile.png", fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.setViewport({ width: 1440, height: 1000 });
  await page.goto(`${base}/#/runs/${created.run.id}`, { waitUntil: "networkidle2" });
  await page.waitForSelector('textarea[aria-label="说点什么"]');
  await page.type('textarea[aria-label="说点什么"]', fixtureText(0));
  await page.click('button[aria-label="发送"]');
  await page.waitForFunction(() => document.querySelector('[data-slot="bubble-content"]')?.textContent?.includes("先投一点"));
  const live = created.run.view({ research: true });
  const second = live.opportunities.find(o => o.actorId === characters[1].id);
  await created.run.humanAction(characters[1].id, { opportunityId: second.id, action: "speak", input: { text: fixtureText(1) } });
  await page.waitForFunction(() => document.querySelectorAll('[data-slot="message"]').length === 2);
  await page.click('.people-list .person-row:nth-of-type(2)');
  await page.locator('.mind-panel [role="tab"] ::-p-text(人物设定)').click();
  await page.waitForFunction(() => document.querySelector('.character-details h2')?.textContent === "苏遥");
  await page.waitForSelector('[data-slot="sheet-overlay"]', { hidden: true });
  assert.equal(await page.$$eval('.character-details', nodes => nodes.length), 1);
  await page.waitForFunction(() => !document.querySelector('[data-slot="sheet-content"]'));
  await page.screenshot({ path: "data/v2-ui/room-desktop.png", fullPage: false });
  assert.equal(await page.$$eval('[data-slot="sheet-content"]', nodes => nodes.length), 0);
  await page.click('button[aria-label="发给谁"]');
  const targets = await page.$$eval('[role="option"]', nodes => nodes.map(n => n.textContent));
  assert.equal(targets.some(t => t.includes("队内")), false);
  await page.locator('::-p-text(私聊 · 苏遥)').click();
  await page.waitForSelector('[role="listbox"]', { hidden: true });
  await page.locator('textarea[aria-label="说点什么"]').fill("我想先单独问问你。");
  await page.waitForFunction(() => document.querySelector('textarea[aria-label="说点什么"]').value === "我想先单独问问你。" && !document.querySelector('button[aria-label="发送"]').disabled);
  const posted = page.waitForResponse(r => r.url().endsWith("/actions") && r.request().method() === "POST");
  await page.click('button[aria-label="发送"]');
  const contactResponse = await posted;
  assert.equal(contactResponse.status(), 200, await contactResponse.text());
  await page.waitForFunction(() => [...document.querySelectorAll('[data-slot="bubble-content"]')].some(n => n.textContent.includes("我想先单独问问你。")));
  await page.waitForFunction(async ({ id, actor }) => {
    const response = await fetch(`/api/v2/runs/${id}?view=research`, { headers: { Authorization: `Bearer ${localStorage.getItem(`society:run:${id}:owner`)}` } });
    const view = await response.json(); return view.opportunities.some(o => o.actorId === actor);
  }, {}, { id: created.run.id, actor: characters[1].id });
  assert.equal(created.run.view({}).events.some(e => e.text === "我想先单独问问你。"), false);
  const contact = created.run.view({ research: true }).opportunities.find(o => o.actorId === characters[1].id);
  assert.equal(contact.channel, "private");
  assert.deepEqual(contact.communications.map(c => c.channel), ["public"]);
  await page.click('button[aria-label="关闭人物详情"]');
  await page.setViewport({ width: 390, height: 844 });
  await page.waitForFunction(() => window.matchMedia('(max-width: 767px)').matches && !document.querySelector('.room-shell .people-list'));
  await page.locator('button[aria-label="查看人物"]').click();
  await page.waitForSelector('[data-slot="sheet-content"][data-state="open"]');
  assert.equal(await page.$$eval('[data-slot="sheet-content"][data-state="open"]', nodes => nodes.length), 1);
  await page.screenshot({ path: "data/v2-ui/people-mobile.png", fullPage: true });
  await page.keyboard.press("Escape");
  await page.waitForSelector('[data-slot="sheet-overlay"]', { hidden: true });
  await page.screenshot({ path: "data/v2-ui/room-mobile.png", fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.goto(`${base}/#/create`, { waitUntil: "networkidle2" });
  await page.screenshot({ path: "data/v2-ui/create-mobile.png", fullPage: true });
  await page.setViewport({ width: 1440, height: 1000 });
  await page.screenshot({ path: "data/v2-ui/create-desktop.png", fullPage: true });
  await page.goto(`${base}/#/characters`, { waitUntil: "networkidle2" });
  await page.screenshot({ path: "data/v2-ui/personality-desktop.png", fullPage: true });
  await page.locator('[role="tab"] ::-p-text(倾向)').click();
  await page.waitForSelector('[aria-label="审慎性设定"]');
  await page.screenshot({ path: "data/v2-ui/traits-desktop.png", fullPage: true });
  await page.locator('button ::-p-text(新人物)').click();
  for (const [key, value] of Object.entries({ name: "测试人物", persona: "愿意尝试，但很在意对方是否认真。", values: "诚实", goals: "交到朋友", voice: "简短" })) await page.type(`#character-${key}`, value);
  await page.click('form button[type="submit"]');
  await page.waitForFunction(() => document.querySelector('.character-details h2')?.textContent === "测试人物");
  await page.waitForSelector('[data-slot="dialog-overlay"]', { hidden: true });
  await page.locator('button ::-p-text(复制)').click();
  await page.waitForFunction(() => document.querySelector('.character-details h2')?.textContent === "测试人物2");
  await page.locator('button ::-p-text(编辑)').click();
  await page.locator('#character-name').fill("修改后的人物");
  await page.click('form button[type="submit"]');
  await page.waitForFunction(() => document.querySelector('.character-details h2')?.textContent === "修改后的人物");
  await page.waitForSelector('[data-slot="dialog-overlay"]', { hidden: true });
  const exported = await (await fetch(`${base}/api/characters/export`)).json();
  assert.equal(exported.characters.length, 2);
  exported.characters[0].displayName = "导入的人物";
  const imported = await fetch(`${base}/api/characters/import`, { method: "POST", headers: { "content-type": "application/json", Authorization: `Bearer ${process.env.SOCIETY_OPERATOR_TOKEN}` }, body: JSON.stringify(exported) });
  assert.equal(imported.status, 201); assert.equal((await imported.json()).added, 1);
  await page.screenshot({ path: "data/v2-ui/characters-desktop.png", fullPage: true });
  // Copy a fully specified built-in, edit only its name, and verify no personality is lost.
  await page.locator('.characters-layout .person-row ::-p-text(林默)').click();
  await page.locator('button ::-p-text(复制)').click();
  await page.waitForFunction(() => document.querySelector('.character-details h2')?.textContent === "林默");
  await page.waitForFunction(() => [...document.querySelectorAll('button')].some(b => b.textContent === "编辑"));
  await page.locator('button ::-p-text(编辑)').click();
  await page.locator('#character-name').fill("人格保留验证");
  await page.click('form button[type="submit"]');
  await page.waitForFunction(() => document.querySelector('.character-details h2')?.textContent === "人格保留验证");
  const preserved = (await (await fetch(`${base}/api/characters/export`)).json()).characters.find(c => c.displayName === "人格保留验证");
  const original = context.characters.list().builtins[0];
  for (const key of ["traits", "temperament", "decisionBiases", "regulation", "autobiographicalAnchors"]) assert.deepEqual(preserved[key], original[key]);
  await page.goto(`${base}/#/create?scenario=public-goods&mode=experiment`, { waitUntil: "networkidle2" });
  assert.equal(await page.$$eval('[data-slot="toggle-group-item"][data-state="on"]', nodes => nodes.some(n => n.textContent === "公共品博弈")), true);
  await page.locator('button ::-p-text(仅文字人设)').click();
  await page.screenshot({ path: "data/v2-ui/experiment-desktop.png", fullPage: true });
  // Advance the human fixture until a committed action is available to inspect.
  for (let step = 0; step < 60 && !created.run.view({ research: true }).events.some(e => e.type === "action"); step++) {
    const opportunity = created.run.view({ research: true }).opportunities[0];
    if (!opportunity) { await new Promise(resolve => setTimeout(resolve, 20)); continue; }
    const tool = fixtureMessages[1].parts.find(p => p.type === "tool-invest");
    await created.run.humanAction(opportunity.actorId, { opportunityId: opportunity.id, action: opportunity.actions[0]?.name ?? "wait", input: opportunity.actions.length ? tool.input : {} });
  }
  assert.equal(created.run.view({ research: true }).events.some(e => e.type === "action"), true);
  created.run.control("pause");
  await page.goto(`${base}/#/research/${created.run.id}`, { waitUntil: "networkidle2" });
  await page.waitForFunction(() => document.body.textContent.includes("他们最后做了什么") && document.body.textContent.includes("投资了 5 点"));
  await page.waitForSelector('[data-sonner-toast]', { hidden: true });
  await page.screenshot({ path: "data/v2-ui/research-desktop.png", fullPage: true });
  await page.locator('[role="tab"] ::-p-text(轨迹)').click();
  await page.locator('button[aria-label="展开提交投资"]').click();
  await page.waitForFunction(() => [...document.querySelectorAll('[data-slot="collapsible-content"]')].some(n => n.textContent.includes('amount')));
  await page.screenshot({ path: "data/v2-ui/tools-dark.png", fullPage: true });
  await page.locator('[data-slot="sidebar-footer"] button[aria-label="切换外观"]').click();
  await page.locator('[role="menuitemradio"] ::-p-text(浅色)').click();
  await page.waitForFunction(() => !document.documentElement.classList.contains("dark"));
  await page.screenshot({ path: "data/v2-ui/tools-light.png", fullPage: true });
  await page.reload({ waitUntil: "networkidle2" });
  assert.equal(await page.evaluate(() => document.documentElement.classList.contains("dark")), false);
  await page.setViewport({ width: 390, height: 844 });
  await page.locator('.mobile-navigation button[aria-label="切换外观"]').click();
  await page.locator('[role="menuitemradio"] ::-p-text(深色)').click();
  await page.waitForFunction(() => document.documentElement.classList.contains("dark"));
  await page.screenshot({ path: "data/v2-ui/research-mobile.png", fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.deepEqual(errors, []);
  console.log("UI passed: home, speech, private reply, mobile Sheet, personality fields survive editing, experiment condition, action evidence, import/export, no overflow or browser errors.");
} finally {
  await browser.close(); context.runs.stopAll(); await created.run.settled(); context.liveConnections.closeAll();
  server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); context.runs.store.close();
}
